document.write("<nav class='navbar navbar-expand-sm'>          ");
document.write("<button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNavDropdown' aria-controls='navbarNavDropdown' aria-expanded='false' aria-label='Toggle navigation'>  <i class='fas fa-bars'></i>  </button>");
document.write("<div class='collapse navbar-collapse' id='navbarNavDropdown'>");
document.write("<ul class='navbar-nav'>");
document.write("<li class='nav-item active'>");
document.write("<a class='nav-link' href='#'>Registration <span class='sr-only'>(current)</span></a>");
document.write("</li>");
document.write("<li class='nav-item'>");
document.write("<a class='nav-link' href='#'>Maintenance</a>");
document.write("</li>");
document.write("<li class='nav-item'>");
document.write("<a class='nav-link' href='#'>Vendor Management</a>");
document.write("</li>");
document.write("<li class='nav-item'>");
document.write("<a class='nav-link' href='#'>Reports</a>");
document.write("</li>");
document.write("</ul>");
document.write("</div>");
document.write("</nav>");
